// Generated by Wrangler on Wed Aug 07 2024 22:39:00 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
	BUCKET_ORIGIN: 'https://r2.clipster.dev';
	CLERK_SECRET_KEY: string;
	BROWSER: DurableObjectNamespace<import('./src/index').Browser>;
	BUCKET: R2Bucket;
	MYBROWSER: Fetcher;
}
