// Generated by Wrangler on Sun Aug 04 2024 14:30:52 GMT-0500 (Central Daylight Time)
// by running `wrangler types`

interface Env {
	BROWSER: DurableObjectNamespace<import("./src/index").Browser>;
	BUCKET: R2Bucket;
	MYBROWSER: Fetcher;
}
